services:
  # ---------------------------------------------------------------------------
  # Configurator – one-time configuration job.
  # This worker service is set to autoDeploy: false so you can run it manually.
  - type: worker
    name: configurator
    autoDeploy: false
    env: docker
    dockerfilePath: Dockerfile.configurator
    envVars:
      - key: DB_HOST
        value: ${DB_HOST}
      - key: DB_PORT
        value: ${DB_PORT}
      - key: REDIS_CACHE
        value: ${REDIS_CACHE}
      - key: REDIS_QUEUE
        value: ${REDIS_QUEUE}
      - key: SOCKETIO_PORT
        value: "9000"
    disk:
      name: sites
      mountPath: /home/frappe/frappe-bench/sites

  # ---------------------------------------------------------------------------
  # Frontend – public web service (runs nginx).
  - type: web
    name: frontend
    env: docker
    dockerfilePath: Dockerfile.frontend
    envVars:
      - key: BACKEND
        value: "backend:8000"
      - key: SOCKETIO
        value: "websocket:9000"
      - key: FRAPPE_SITE_NAME_HEADER
        # Note: The '$' in $host is escaped here.
        value: '${FRAPPE_SITE_NAME_HEADER:-\$host}'
      - key: UPSTREAM_REAL_IP_ADDRESS
        value: "${UPSTREAM_REAL_IP_ADDRESS:-127.0.0.1}"
      - key: UPSTREAM_REAL_IP_HEADER
        value: "${UPSTREAM_REAL_IP_HEADER:-X-Forwarded-For}"
      - key: UPSTREAM_REAL_IP_RECURSIVE
        value: "${UPSTREAM_REAL_IP_RECURSIVE:-off}"
      - key: PROXY_READ_TIMEOUT
        value: "${PROXY_READ_TIMEOUT:-120}"
      - key: CLIENT_MAX_BODY_SIZE
        value: "${CLIENT_MAX_BODY_SIZE:-50m}"
    disk:
      name: sites
      mountPath: /home/frappe/frappe-bench/sites

  # ---------------------------------------------------------------------------
  # Backend – internal web service.
  - type: web
    name: backend
    env: docker
    dockerfilePath: Dockerfile.backend
    disk:
      name: sites
      mountPath: /home/frappe/frappe-bench/sites

  # ---------------------------------------------------------------------------
  # Websocket – internal service running the socket.io process.
  - type: web
    name: websocket
    env: docker
    dockerfilePath: Dockerfile.websocket
    disk:
      name: sites
      mountPath: /home/frappe/frappe-bench/sites

  # ---------------------------------------------------------------------------
  # Queue Worker (short) – background worker for short/fast queues.
  - type: worker
    name: queue-short
    env: docker
    dockerfilePath: Dockerfile.queue_short
    disk:
      name: sites
      mountPath: /home/frappe/frappe-bench/sites

  # ---------------------------------------------------------------------------
  # Queue Worker (long) – background worker for long queues.
  - type: worker
    name: queue-long
    env: docker
    dockerfilePath: Dockerfile.queue_long
    disk:
      name: sites
      mountPath: /home/frappe/frappe-bench/sites

  # ---------------------------------------------------------------------------
  # Scheduler – background service to run scheduled tasks.
  - type: worker
    name: scheduler
    env: docker
    dockerfilePath: Dockerfile.scheduler
    disk:
      name: sites
      mountPath: /home/frappe/frappe-bench/sites
